//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestGroup.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testgroupEntities : DbContext
    {
        public testgroupEntities()
            : base("name=testgroupEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<StudentTestGroup> StudentTestGroup { get; set; }
        public virtual DbSet<StudentTestGroup_Unit_Junction> StudentTestGroup_Unit_Junction { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<ExtendQuestion> ExtendQuestion { get; set; }
    }
}
