//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestGroup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTestGroup_Unit_Junction
    {
        public string StudentID { get; set; }
        public string UnitID { get; set; }
        public bool VideoWatched { get; set; }
        public long VideoElapsedTime { get; set; }
        public string Answer { get; set; }
        public Nullable<bool> Result { get; set; }
        public long QuestionElapsedTime { get; set; }
        public bool ChatbotFinished { get; set; }
        public long ChatbotElapsedTime { get; set; }
        public string ConceptMapAnswer { get; set; }
        public string ExtendQuestionAnswer { get; set; }
        public Nullable<bool> ExtendQuestionResult { get; set; }
    
        public virtual StudentTestGroup StudentTestGroup { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
